[project]
name = "personal-website"
version = "0.1.0"
description = "Lucky Mehra website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ghp-import>=2.1.0",
    "pelican[markdown]>=4.11.0",
]
